apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: izjxmn5s9-go 
  janus-idp.io/tekton: izjxmn5s9-go
  backstage.io/kubernetes-id: izjxmn5s9-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: izjxmn5s9-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml